INSERT INTO foods (category,name,calories) VALUES
('Candy','Butterfinger candy bar',290),
('Candy','Caramel candy',27),
('Candy','Chewing gum (made with sugar)',10),
('Candy','Chewing gum (sugar-free)',5),
('Candy','Chocolate chips',201),
('Candy','Chocolate-covered almonds',17),
('Candy','Chocolate-covered candy',73),
('Candy','Coconut candy, chocolate-covered',243),
('Candy','Dark chocolate candy bar',207),
('Candy','Dietetic chocolate-covered candy',40),
('Candy','Dietetic hard candy',14),
('Candy','Fast Break candy bar (Reeses)',282),
('Candy','Fruit roll-up (fruit snack chews)',104),
('Candy','Hard candy',102),
('Candy','Krackel or Crunch Bar',169),
('Candy','M&Ms candies with peanuts',243),
('Candy','M&Ms plain chocolate candies',236),
('Candy','Marshmallows',23),
('Candy','Milk chocolate bar with almonds',216),
('Candy','Milk chocolate fruit & nut bar',150),
('Candy','Milky Way candy bar',228),
('Candy','Peanut brittle',44),
('Candy','Peanut butter cups (Reeses)',232),
('Candy','Popsicle',63),
('Candy','Slurpee or snow cone',424),
('Candy','Snickers candy bar',273),
('Candy','Sugar-free popsicle (diet)',17),
('Candy','Taffy',37),
('Candy','Tootsie roll',139),
('Candy','Twix cookie bars',289),
('Carbohydrates','100% whole wheat bagel',277),
('Carbohydrates','100% whole wheat bread',69),
('Carbohydrates','100% whole wheat cracker (Triscuit)',18),
('Carbohydrates','All-Bran cereal',156),
('Carbohydrates','Almonds',164),
('Carbohydrates','Angel food cake',143),
('Carbohydrates','Animal cracker',64),
('Carbohydrates','Apple crisp',192),
('Carbohydrates','Apple Jacks cereal',117),
('Carbohydrates','Apple pie with crumb topping',363),
('Carbohydrates','Apple pie, two crust',356),
('Carbohydrates','Au gratin potatoes',154),
('Carbohydrates','Bagel (plain)',289),
('Carbohydrates','Baked beans',118),
('Carbohydrates','Baked or low-fat tortilla chips',87),
('Carbohydrates','Baked potato, plain (dont eat peel)',121),
('Carbohydrates','Baked potato, plain (eat peel)',159),
('Carbohydrates','Baked Pringles potato chips',131),
('Carbohydrates','Baked sweet potato',101),
('Carbohydrates','Baked winter squash',38),
('Carbohydrates','Baked, broiled, or sauteed shrimp',112),
('Soup','Bean soup',137),
('Soup','Bean soup with ham',221),
('Soup','Bean soup with macaroni',154),
('Carbohydrates','Biscotti',145),
('Carbohydrates','Blueberry or banana muffin',313),
('Carbohydrates','Blueberry pancakes',152),
('Carbohydrates','Boiled potatoes',156),
('Carbohydrates','Bran flakes cereal',144),
('Carbohydrates','Bran muffin',333),
('Carbohydrates','Bran, multigrain, or wheat waffle',115),
('Carbohydrates','Brazil nuts',230),
('Carbohydrates','Bread stick',41),
('Carbohydrates','Bread stuffing',176),
('Carbohydrates','Breakfast bar',139),
('Carbohydrates','Brown rice, no fat added',107),
('Carbohydrates','Brownie with icing',170),
('Carbohydrates','Brownie, no icing',129),
('Carbohydrates','Bulgur, no fat added',56),
('Carbohydrates','Buttered popcorn',458),
('Carbohydrates','Buttermilk biscuit',186),
('Carbohydrates','Cake doughnut',198),
('Carbohydrates','Cake doughnut, frosted',251),
('Carbohydrates','Candied sweet potato',146),
('Carbohydrates','Capn Crunch cereal',144),
('Carbohydrates','Caramel corn',151),
('Carbohydrates','Carrot cake with icing',326),
('Carbohydrates','Cashews',165),
('Carbohydrates','Cheerios',111),
('Carbohydrates','Cheese blintz',134),
('Carbohydrates','Cheese bread',71),
('Carbohydrates','Cheese cracker',67),
('Carbohydrates','Cheese Danish pastry',419),
('Carbohydrates','Cheese enchilada',226),
('Carbohydrates','Cheese manicotti with tomato sauce',458),
('Carbohydrates','Cheese nachos',472),
('Carbohydrates','Cheese pizza, thick crust',203),
('Carbohydrates','Cheese pizza, thin crust',164),
('Carbohydrates','Cheese quesadilla',498),
('Carbohydrates','Cheese ravioli (no sauce)',185),
('Carbohydrates','Cheese sandwich cracker',33),
('Carbohydrates','Cheese tortellini with cream sauce',390),
('Carbohydrates','Cheese tortellini with tomato sauce',333),
('Carbohydrates','Cheese tortellini, no sauce',354),
('Carbohydrates','Cheesecake',410),
('Carbohydrates','Chex cereal (corn, wheat, or bran)',143),
('Carbohydrates','Chickpeas',148),
('Carbohydrates','Chocolate cake with icing',246),
('Carbohydrates','Chocolate chip cookie',48),
('Carbohydrates','Chocolate chip muffin',364),
('Carbohydrates','Chocolate cream pie',380),
('Carbohydrates','Chocolate cupcake with icing/filling',150),
('Carbohydrates','Chocolate fudge cookie',56),
('Carbohydrates','Chocolate raised doughnut, frosted',275),
('Carbohydrates','Chocolate wafer cookie',52),
('Carbohydrates','Chocolate-covered granola bar',171),
('Carbohydrates','Chow fun rice noodles',171),
('Carbohydrates','Cinnamon bread or toast',69),
('Carbohydrates','Cinnamon Toast Crunch cereal',160),
('Carbohydrates','Cocoa Puffs cereal',117),
('Carbohydrates','Coconut milk',138),
('Carbohydrates','Coffee cake',160),
('Carbohydrates','Coffee Mate Lite  (powder)',13),
('Carbohydrates','Cooked barley',99),
('Carbohydrates','Corn chips (Fritos)',237),
('Carbohydrates','Corn flakes cereal',90),
('Carbohydrates','Corn puffs (Cheetos)',194),
('Carbohydrates','Corn tortilla',53),
('Carbohydrates','Cornbread or corn muffin',174),
('Carbohydrates','Cornbread stuffing',179),
('Carbohydrates','Couscous, no fat added',87),
('Carbohydrates','Cracked wheat English muffin',129),
('Soup','Cream of potato soup',136),
('Carbohydrates','Cream of wheat',55),
('Carbohydrates','Cream puff or éclair',267),
('Carbohydrates','Croissant',231),
('Carbohydrates','Croutons',47),
('Carbohydrates','Diet high-fiber bread',60),
('Carbohydrates','Diet high-fiber multigrain bread',61),
('Carbohydrates','Dry beans, cooked with fat',165),
('Carbohydrates','Dry beans, cooked without fat',110),
('Carbohydrates','Dry blackeye peas, cooked without fat',97),
('Carbohydrates','Egg noodles (no fat added)',211),
('Carbohydrates','Egg noodles with butter or oil',252),
('Carbohydrates','English muffin',136),
('Carbohydrates','English muffin with raisins',141),
('Carbohydrates','Fat-free berry or banana muffin',295),
('Carbohydrates','Fat-free cheese Danish pastry',95),
('Carbohydrates','Fat-free coffee cake',94),
('Carbohydrates','Fiber One cereal',118),
('Carbohydrates','Fig bar (Fig Newton)',56),
('Carbohydrates','Filberts (hazelnuts)',176),
('Carbohydrates','Flax seed',45),
('Carbohydrates','Flour (wheat) tortilla',166),
('Carbohydrates','foccacia',182),
('Carbohydrates','Fortified high energy bar (Powerbar)',229),
('Carbohydrates','Fortune cookie',30),
('Carbohydrates','French bread',175),
('Carbohydrates','French fries, deep-fried',457),
('Carbohydrates','French toast',158),
('Carbohydrates','French toast sticks',386),
('Carbohydrates','Fried wonton',54),
('Carbohydrates','Froot Loops cereal',110),
('Carbohydrates','Frosted Flakes cereal',150),
('Carbohydrates','Frosted Mini-Wheats cereal',204),
('Carbohydrates','Frosted sweet roll or cinnamon bun',227),
('Carbohydrates','Fruit blintz',123),
('Carbohydrates','Fruit bread (banana, etc.)',132),
('Carbohydrates','Fruit shortcake with whipped cream',211),
('Carbohydrates','Fruit-filled Danish pastry',263),
('Carbohydrates','Fruity Pebbles cereal',144),
('Carbohydrates','Garlic bread',96),
('Carbohydrates','Golden Grahams cereal',149),
('Carbohydrates','Graham cracker',59),
('Carbohydrates','Granola bar',130),
('Carbohydrates','Granola cereal (homemade)',299),
('Carbohydrates','Grape-Nuts cereal',98),
('Carbohydrates','Grits, no fat added',56),
('Carbohydrates','Grits, with butter',89),
('Carbohydrates','Hard pretzels',38),
('Carbohydrates','Hash browns',157),
('Carbohydrates','Home fries',179),
('Carbohydrates','Honey Bunches of Oats cereal',158),
('Carbohydrates','Honey Nut Cheerios',112),
('Carbohydrates','Honey Smacks cereal',151),
('Carbohydrates','Honeycomb cereal',87),
('Carbohydrates','Hummus',27),
('Carbohydrates','Hush puppy',74),
('Carbohydrates','Ice cream cake',91),
('Carbohydrates','Ice cream cone (sugar cone, shell only)',40),
('Carbohydrates','Ice cream cone (wafer or cake, shell only)',17),
('Carbohydrates','Jelly doughnut',221),
('Carbohydrates','Kashi, puffed',88),
('Carbohydrates','Kix cereal',83),
('Carbohydrates','Lemon meringue pie',367),
('Soup','Lentil soup',181),
('Carbohydrates','Lentils',110),
('Carbohydrates','Life cereal (plain & cinnamon)',165),
('Carbohydrates','Low-fat corn puffs (cheese curls)',104),
('Carbohydrates','Low-fat granola cereal',209),
('Carbohydrates','Low-fat popcorn',327),
('Carbohydrates','Lowfat bran & fruit muffin',136),
('Carbohydrates','Lowfat granola bar',95),
('Carbohydrates','Lowfat waffle',87),
('Carbohydrates','Macadamia nuts',203),
('Carbohydrates','Marshmallow rice krispies bar',113),
('Carbohydrates','Mashed potatoes (with butter)',116),
('Carbohydrates','Mashed potatoes (with milk and butter)',109),
('Carbohydrates','Mashed potatoes (with milk, no butter)',85),
('Carbohydrates','Matzo',111),
('Carbohydrates','Matzo ball',48),
('Carbohydrates','Matzo pancake',54),
('Carbohydrates','Meal replacement bar (Slim Fast bar)',143),
('Carbohydrates','Meatless bacon bits',33),
('Carbohydrates','Meatless fried chicken (breaded)',84),
('Carbohydrates','Meatless hot dog (no bun)',163),
('Carbohydrates','Meatless sausage',64),
('Carbohydrates','Melba toast',20),
('Soup','Miso soup',84),
('Carbohydrates','Mixed nuts',175),
('Carbohydrates','Mole poblana sauce',78),
('Carbohydrates','Moon pie',328),
('Carbohydrates','Multigrain bread',65),
('Carbohydrates','Mung bean noodles',160),
('Carbohydrates','Oatmeal (flavored)',106),
('Carbohydrates','Oatmeal (plain)',73),
('Carbohydrates','Oatmeal raisin cookie',59),
('Carbohydrates','Oreo or thin mint cookie',52),
('Carbohydrates','Pancakes',183),
('Carbohydrates','Peach cobbler',209),
('Carbohydrates','Peanut butter',96),
('Carbohydrates','Peanut butter & jelly spread',65),
('Carbohydrates','Peanut butter cookie',76),
('Carbohydrates','Peanut butter sandwich cracker',12),
('Carbohydrates','Peanut butter, reduced fat',94),
('Carbohydrates','Peanut sauce',44),
('Carbohydrates','Peanuts',170),
('Carbohydrates','Pecan pie',456),
('Carbohydrates','Pecans',196),
('Carbohydrates','Pine nuts (pignolias)',58),
('Carbohydrates','Pistachios',82),
('Carbohydrates','Pita bread (100% whole wheat)',120),
('Carbohydrates','Pita bread (white)',124),
('Carbohydrates','Plain Danish pastry',262),
('Carbohydrates','Plain muffin',345),
('Carbohydrates','Pop Tart',204),
('Carbohydrates','Pork & beans',124),
('Carbohydrates','Potato chips, regular (all flavors)',107),
('Carbohydrates','Potato pancake (latke)',70),
('Carbohydrates','Potato pudding',144),
('Carbohydrates','Potato salad',129),
('Carbohydrates','Potato salad with egg',131),
('Carbohydrates','Potato skin with cheese & bacon',1667),
('Carbohydrates','Pound cake',350),
('Carbohydrates','Protein powder',37),
('Carbohydrates','Pumpkin pie',323),
('Carbohydrates','Raised doughnut',242),
('Carbohydrates','Raised doughnut, frosted',275),
('Carbohydrates','Raisin bagel',288),
('Carbohydrates','Raisin bread',71),
('Carbohydrates','Raisins',27),
('Carbohydrates','Reduced fat cheese cracker',50),
('Carbohydrates','Reduced-fat chocolate chip cookie',47),
('Carbohydrates','Reduced-fat oatmeal raisin cookie',52),
('Carbohydrates','Reduced-fat Oreo',46),
('Carbohydrates','Reduced-fat snack cracker',12),
('Carbohydrates','Reduced-fat Triscuit',16),
('Carbohydrates','Refried beans',182),
('Carbohydrates','Refrigerated biscuit (canned dough)',66),
('Carbohydrates','Roasted chestnuts',69),
('Carbohydrates','Roasted potatoes',179),
('Carbohydrates','Romaine lettuce',2),
('Carbohydrates','Rye bread',67),
('Carbohydrates','Saltine cracker',13),
('Carbohydrates','Sesame seeds',53),
('Carbohydrates','Shortbread cookie',35),
('Carbohydrates','Shredded sweetened coconut',110),
('Carbohydrates','Snack cracker',15),
('Carbohydrates','Snack Mix (pretzel, nut, cereal mix)',47),
('Carbohydrates','Soft pretzel',389),
('Carbohydrates','Sourdough bread',69),
('Carbohydrates','Soy burger (no bun)',125),
('Carbohydrates','Soy nuts',110),
('Carbohydrates','Soy sauce',8),
('Carbohydrates','Spaghetti, macaroni, or pasta (plain)',196),
('Soup','Split pea soup with ham',195),
('Carbohydrates','Split peas',115),
('Carbohydrates','Stuffed baked potato (with cheese)',195),
('Carbohydrates','Stuffed baked potato (with sour cream)',158),
('Carbohydrates','Sub roll',262),
('Carbohydrates','Sugar cookie',76),
('Carbohydrates','Sunflower seeds',162),
('Carbohydrates','Taco or tostada shell',62),
('Carbohydrates','Tator tots',142),
('Carbohydrates','Teriyaki sauce',54),
('Carbohydrates','Tofu',38),
('Carbohydrates','Tofutti tofu frozen dessert',180),
('Carbohydrates','Tortilla chips (Doritos, Tostitos)',160),
('Soup','Tortilla soup',238),
('Carbohydrates','Total cereal',107),
('Carbohydrates','Trail mix (nuts, seeds, dried fruit)',176),
('Carbohydrates','Trix cereal',117),
('Carbohydrates','Upside down cake (with fruit)',275),
('Carbohydrates','Vanilla sandwich cookie',53),
('Carbohydrates','Vanilla wafer',18),
('Carbohydrates','Vegetable oil (canola, corn, olive, etc)',40),
('Carbohydrates','Vegetable pizza, thick crust',193),
('Carbohydrates','Vegetable pizza, thin crust',149),
('Carbohydrates','Vegetarian chili',136),
('Carbohydrates','Vegetarian meatloaf or patty',110),
('Carbohydrates','Veggie burger (no bun)',127),
('Carbohydrates','Waffle',103),
('Carbohydrates','Walnuts',185),
('Carbohydrates','Wheat Bagel (part whole wheat)',300),
('Carbohydrates','Wheat bran, unprocessed',31),
('Carbohydrates','Wheat cracker',56),
('Carbohydrates','Wheat or cracked wheat bread',65),
('Carbohydrates','Wheat roll (part whole wheat)',82),
('Carbohydrates','Wheaties cereal',107),
('Carbohydrates','White bread',69),
('Carbohydrates','White cake with icing',415),
('Carbohydrates','White rice, no fat added',102),
('Carbohydrates','White rice, with butter or oil',118),
('Carbohydrates','White roll',78),
('Carbohydrates','Whole wheat English muffin',118),
('Carbohydrates','Whole wheat pancakes',183),
('Carbohydrates','Whole wheat spaghetti or pasta (plain)',172),
('Carbohydrates','Whole wheat tortilla',105),
('Carbohydrates','Wild rice, no fat added',65),
('Carbohydrates','Worcestershire sauce',4),
('Carbohydrates','Yellow cake with icing',400),
('Carbohydrates','Zucchini bread',150),
('Dairy','1% milk (low fat)',102),
('Dairy','2% milk (reduced fat)',122),
('Dairy','Alfredo sauce',249),
('Dairy','American cheese (processed)',71),
('Dairy','Butter',36),
('Dairy','Buttermilk',98),
('Dairy','Cheese (cheddar, Swiss)',114),
('Dairy','Cheese sauce',109),
('Dairy','Cheese sauce, low fat',80),
('Dairy','Cheese spread or dip',100),
('Dairy','Chocolate flavored drink',129),
('Dairy','Chocolate milk, 1% (low fat)',158),
('Dairy','Chocolate milk, 2% (reduced fat)',175),
('Dairy','Chocolate milk, fat free (skim)',140),
('Dairy','Chocolate milk, whole milk',208),
('Dairy','Cool Whip',60),
('Dairy','Cottage cheese, creamed',108),
('Dairy','Cream cheese (regular)',51),
('Dairy','Cream cheese dip',106),
('Dairy','Deviled egg',62),
('Dairy','Diet pudding (instant or canned)',105),
('Dairy','Dry milk powder, low fat',110),
('Dairy','Egg & sausage on biscuit',565),
('Dairy','Egg Beaters',60),
('Soup','Egg drop soup',73),
('Dairy','Egg salad',353),
('Dairy','Egg white',17),
('Dairy','Egg, cheese & bacon on biscuit',438),
('Dairy','Egg, cheese & ham on English muffin',312),
('Dairy','Egg, cheese & sausage on English muffin',458),
('Dairy','Fat free milk (skim)',83),
('Dairy','Fat-free American cheese',31),
('Dairy','Fat-free spread (margarine type)',2),
('Dairy','Feta or goat cheese',99),
('Dairy','Flavored soymilk',118),
('Dairy','Flavored yogurt, fat-free sugar-free',98),
('Dairy','Flavored yogurt, low fat',193),
('Dairy','Flavored yogurt, whole milk',229),
('Dairy','Fried cheese sticks',503),
('Dairy','Fried egg',89),
('Dairy','Frozen yogurt, low fat',214),
('Dairy','Frozen yogurt, low fat sugar free',199),
('Dairy','Frozen yogurt, whole milk',221),
('Dairy','Fruit ice (Italian fruit ice)',124),
('Dairy','fruit smoothie made with milk',496),
('Dairy','Fruit yogurt, fat-free sugar-free',87),
('Dairy','Fruit yogurt, low fat',173),
('Dairy','Fruit yogurt, whole milk',202),
('Dairy','Grilled cheese sandwich',290),
('Dairy','Half & Half',39),
('Dairy','Hard or soft boiled egg',77),
('Dairy','Ice cream bar, chocolate covered',169),
('Dairy','Ice cream sandwich',143),
('Dairy','Ice cream, regular',267),
('Dairy','Ice cream, rich',369),
('Dairy','Instant cocoa (with water)',113),
('Dairy','Instant cocoa, diet (with water)',57),
('Dairy','Jello',74),
('Dairy','Jello with fruit',78),
('Dairy','Light butter',25),
('Dairy','Light cream',59),
('Dairy','Light fudgesicle',122),
('Dairy','Light ice cream',216),
('Dairy','Light ice cream bar',153),
('Dairy','Light ice cream sandwich',130),
('Dairy','Light soft serve ice cream',221),
('Dairy','Low fat cheddar or Swiss',48),
('Dairy','Low fat cream cheese',35),
('Dairy','Low fat ice cream',229),
('Dairy','Low fat, low sugar ice milk',153),
('Dairy','Low lactose fat free (skim) milk',83),
('Dairy','Low lactose lowfat (1%) milk',102),
('Dairy','Low lactose reduced fat (2%) milk',122),
('Dairy','Low lactose whole milk',146),
('Dairy','Lowfat Cool Whip',41),
('Dairy','Lowfat cottage cheese',81),
('Dairy','Malted milk (Ovaltine)',174),
('Dairy','Meal replacement drink (Slim Fast)',174),
('Dairy','Meal replacement powder (Slim Fast)',49),
('Dairy','Milk chocolate bar or candy (plain)',332),
('Dairy','Milk gravy',88),
('Dairy','Milk shake (whole milk)',393),
('Dairy','Milk shake, low fat',199),
('Dairy','Mozzarella cheese (part skim)',86),
('Dairy','Nonfat dry milk, reconstituted',81),
('Dairy','Parmesan or Romano cheese',22),
('Dairy','Plain yogurt, fat free',127),
('Dairy','Plain yogurt, whole milk',138),
('Dairy','Pudding (instant or canned)',133),
('Dairy','Pudding, no sugar added',81),
('Dairy','Reduced-calorie spread (margarine type)',17),
('Dairy','Ricotta cheese',96),
('Dairy','Scrambled egg (cooked with fat)',94),
('Dairy','Scrambled egg (cooked without fat)',78),
('Dairy','Sherbet',278),
('Dairy','Soft serve ice cream',348),
('Dairy','Sour cream',64),
('Dairy','Sour cream dip',134),
('Dairy','Sour cream, low fat or light',44),
('Dairy','Soymilk',98),
('Dairy','Stick margarine',35),
('Dairy','Sugar-free Jello (diet)',4),
('Dairy','Sugar-free Jello with fruit (diet)',40),
('Dairy','Sweetened condensed milk',246),
('Dairy','Tub margarine',34),
('Dairy','Tub spread (margarine type)',25),
('Dairy','Whipped butter',27),
('Dairy','Whipped cream, sweetened',104),
('Dairy','White sauce (cream sauce)',91),
('Dairy','Whole milk',146),
('Drinks','100% Fruit juice blend (Juicy Juice)',133),
('Drinks','Beer or ale',148),
('Drinks','Bloody Mary',115),
('Drinks','Brandy or cognac',128),
('Drinks','Cappuccino',160),
('Drinks','Club soda (seltzer)',0),
('Drinks','Coffee',14),
('Drinks','Coffee Mate (liquid)',41),
('Drinks','Coffee Mate (powder)',16),
('Drinks','Coffee Mate Lite (liquid)',21),
('Drinks','Cordial or liqueur',71),
('Drinks','Cranberry juice cocktail',144),
('Drinks','Crystal Lite (low-calorie fruit drink)',46),
('Drinks','Dessert wine (all)',165),
('Drinks','Fitness Water (Propel)',12),
('Drinks','Fruit drink (punch, ade, or cooler)',119),
('Drinks','Gatorade or Powerade (sports drink)',60),
('Drinks','Gin',110),
('Drinks','Gin & tonic',160),
('Drinks','Latte',143),
('Drinks','Lemonade',99),
('Drinks','Liqueur with cream',203),
('Drinks','Lite beer',101),
('Drinks','Manhattan',138),
('Drinks','Margarita',426),
('Drinks','Martini',130),
('Drinks','Pedialyte',25),
('Drinks','Pina colada',418),
('Drinks','Rum',97),
('Drinks','Rum & coke',274),
('Drinks','Sangria',164),
('Drinks','Soft drink, diet',5),
('Drinks','Soft drink, regular',155),
('Drinks','Table wine (all)',114),
('Drinks','Tea (sweetened)',53),
('Drinks','Tea (unsweetened)',2),
('Drinks','Tonic water (quinine water)',124),
('Drinks','Vodka or tequila',97),
('Drinks','Water',0),
('Drinks','Whiskey (bourbon, scotch, rye)',105),
('Drinks','Wine cooler',111),
('Fats','Bacon grease (or meat drippings)',108),
('Fats','Blue cheese dressing',77),
('Fats','Creamy dressing (ranch)',71),
('Fats','Fat-free Italian dressing',7),
('Fats','Fat-free mayonnaise-type dressing',13),
('Fats','Fat-free ranch dressing',18),
('Fats','Fat-free thousand island dressing',21),
('Fats','French dressing',71),
('Fats','Italian dressing (oil & vinegar)',43),
('Fats','Low-calorie mayonnaise',145),
('Fats','Low-calorie salad dressing',24),
('Fats','Mayonnaise, regular',99),
('Fats','Miracle whip salad dressing',57),
('Fats','Popcorn (oil popped, no butter)',440),
('Fats','Sweet & sour dressing',2),
('Fats','Thousand island dressing',58),
('Fats','Vegetable shortening',37),
('Fruit','All-fruit preserves (no added sugar)',37),
('Fruit','Ambrosia',50),
('Fruit','Apple (raw)',72),
('Fruit','Apple chips',101),
('Fruit','Apple cider',117),
('Fruit','Apple juice (100% juice)',117),
('Fruit','Applesauce (sweetened)',97),
('Fruit','Applesauce (unsweetened)',52),
('Fruit','Apricot (canned, light syrup)',15),
('Fruit','Apricot (raw)',17),
('Fruit','Avocado',60),
('Fruit','Baked apple (sweetened)',162),
('Fruit','Banana',105),
('Fruit','Banana chips',66),
('Fruit','Blueberries (raw)',41),
('Fruit','Cantaloupe',30),
('Fruit','Cassava',32),
('Fruit','Cassava bread',299),
('Fruit','Cassava with creole sauce',308),
('Fruit','Fried plantain',249),
('Fruit','Jam or preserves (low sugar)',26),
('Fruit','Plantain (boiled or baked)',137),
('Soup','Plantain soup',98),
('Fruit','Strawberries (cooked or canned in syrup)',117),
('Fruit','Strawberries (raw)',23),
('Fruit','Sweet cherries (raw)',37),
('Fruit','Tangerine (raw)',37),
('Fruit','Taro (cocoyam), boiled',106),
('Fruit','Waldorf salad (apple salad in dressing)',121),
('Fruit','Watermelon (raw)',23),
('Meal','Taquitoes',191),
('Protein','Anchovy',95),
('Protein','Bacon',43),
('Protein','Bacon cheeseburger on bun',746),
('Protein','Baked battered fish fillet',155),
('Protein','Baked chicken breast (eat skin)',191),
('Protein','Baked chicken breast (no skin)',141),
('Protein','Baked chicken dark meat (eat skin)',262),
('Protein','Baked chicken dark meat (no skin)',180),
('Protein','Baked chicken drumstick (no skin)',75),
('Protein','Baked chicken thigh (no skin)',108),
('Protein','Baked fish',142),
('Protein','Baked or broiled catfish',116),
('Protein','Baked or broiled cod',113),
('Protein','Baked or broiled flounder',173),
('Protein','Baked or broiled perch',128),
('Protein','Baked or broiled salmon',243),
('Protein','Baked or broiled scallops',125),
('Protein','Baked or broiled trout',306),
('Protein','Baked or broiled tuna',228),
('Protein','Battered fried chicken (eat skin)',249),
('Protein','Battered fried chicken breast',365),
('Protein','Battered fried chicken breast, no skin',253),
('Protein','BBQ short ribs with sauce',108),
('Protein','BBQ spareribs & sauce (eat lean & fat)',124),
('Protein','BBQ spareribs & sauce (eat lean only)',66),
('Protein','Bean and cheese burrito',519),
('Protein','Bean burrito',295),
('Protein','Bean enchilada',179),
('Protein','Bean taco (cheese, lettuce, tomato, salsa)',143),
('Protein','Beef and bean burrito',331),
('Protein','Beef and bean nachos',566),
('Protein','Beef and cheese burrito (no beans)',689),
('Protein','Beef and cheese enchilada',213),
('Protein','Beef brisket',97),
('Protein','Beef broth or consomme',17),
('Protein','Beef burrito (no beans)',297),
('Protein','Beef chimachanga',337),
('Protein','Beef curry',216),
('Protein','Beef fajitas with veggies',397),
('Protein','Beef gravy',31),
('Protein','Beef jerky',39),
('Protein','Beef sirloin frozen meal',275),
('Protein','Beef sloppy joe (no bun)',186),
('Protein','Beef soft taco',262),
('Protein','Beef stew, potatoes & vegetables',199),
('Protein','Beef stroganoff with noodles',343),
('Protein','Beef taco (cheese, lettuce, tomato, salsa)',173),
('Protein','Beef taco with cheese and lettuce',220),
('Protein','Beef with BBQ sauce',229),
('Protein','Beef, bean, and cheese burrito',671),
('Protein','Beef, tomato sauce & noodles',276),
('Protein','Beef, veggies & noodles (tomato sauce)',232),
('Protein','Bologna',86),
('Protein','Bratwurst',281),
('Protein','Breaded fried steak (eat lean & fat)',802),
('Protein','Breaded fried steak (eat lean only)',515),
('Protein','Breaded pork chop (eat lean & fat)',304),
('Protein','Breaded pork chop (eat lean only)',226),
('Protein','Breakfast sausage (brown & serve)',107),
('Protein','Broiled veal chop',230),
('Protein','Buffalo wing (chicken wing & sauce)',73),
('Protein','Canadian bacon',43),
('Protein','Canned tuna (in oil)',158),
('Protein','Canned tuna (in water)',97),
('Protein','Cheeseburger, plain on bun',317),
('Protein','Chicken & cheese quesadilla',563),
('Protein','Chicken and dumplings',184),
('Protein','Chicken and rice with cream sauce',177),
('Protein','Chicken and rice with tomato sauce',113),
('Protein','Chicken cacciatore',382),
('Protein','Chicken chimichanga',558),
('Protein','Chicken chow mein with noodles',275),
('Protein','Chicken cordon bleu',502),
('Protein','Chicken curry',248),
('Protein','Chicken enchilada',203),
('Protein','Chicken fajitas with veggies & guacamole',361),
('Protein','Chicken fettuccine diet frozen meal',265),
('Protein','Chicken gravy',47),
('Soup','Chicken gumbo soup',56),
('Protein','Chicken liver pate',57),
('Protein','Chicken nachos',543),
('Soup','Chicken noodle soup',75),
('Protein','Chicken nuggets',217),
('Protein','Chicken or pork fried rice',166),
('Protein','Chicken or turkey pot pie',488),
('Protein','Chicken Parmigiana',324),
('Protein','Chicken patty or fillet (breaded)',226),
('Soup','Chicken rice soup',60),
('Protein','Chicken salad (with celery, mayo)',208),
('Protein','Chicken salad spread',208),
('Protein','Chicken sandwich with mayo',265),
('Protein','Chicken soft taco',251),
('Protein','Chicken teriyaki',191),
('Protein','Chicken Teriyaki frozen meal',361),
('Soup','Chicken vegetable soup',136),
('Protein','Chicken with BBQ sauce',234),
('Protein','Chicken with rice diet frozen meal',272),
('Protein','Chicken, veggies & noodles (cream sauce)',251),
('Protein','Chili con carne (with beans)',132),
('Protein','Chopped chicken liver',118),
('Soup','Chunky beef vegetable soup',170),
('Protein','Club sandwich (chicken, bacon, tomato)',546),
('Protein','Corn dog (hot dog, cornbread coating)',280),
('Protein','Fried beef liver',148),
('Protein','Fried breaded fish fillet',126),
('Protein','Fried calamari (fried squid)',74),
('Protein','Fried catfish (breaded or battered)',182),
('Protein','Fried chicken breast (no skin)',158),
('Protein','Fried chicken drumstick (battered)',194),
('Protein','Fried chicken fillet sandwich',323),
('Protein','Fried chicken frozen meal',1025),
('Protein','Fried chicken liver',372),
('Protein','Fried chicken thigh (battered)',239),
('Protein','Fried chicken thigh (eat skin)',158),
('Protein','Fried chicken thigh (no skin)',111),
('Protein','Fried chicken wing (battered)',160),
('Protein','Fried chicken wing (no coating)',102),
('Protein','Fried clams (battered)',111),
('Protein','Fried cod (breaded or battered)',190),
('Protein','Fried fish (breaded or battered)',267),
('Protein','Fried fish sandwich with tartar sauce',374),
('Protein','Fried oysters (breaded or battered)',55),
('Protein','Fried pork chop (eat lean & fat)',226),
('Protein','Fried pork chop (eat lean only)',153),
('Protein','Fried pork rinds',174),
('Protein','Fried rice (plain)',125),
('Protein','Fried scallops (floured or breaded)',145),
('Protein','Fried shrimp (breaded or battered)',274),
('Protein','Fried steak (eat lean & fat)',588),
('Protein','Fried steak (eat lean only)',359),
('Protein','Fried tofu',168),
('Protein','Fried whiting (floured or breaded)',191),
('Protein','Grilled pork chop (eat lean & fat)',216),
('Protein','Grilled pork chop (eat lean only)',175),
('Protein','Grilled steak (eat lean & fat)',516),
('Protein','Grilled steak (eat lean only)',307),
('Protein','Ground beef (75% lean, regular)',235),
('Protein','Ground beef (80% lean)',237),
('Protein','Ground beef (85% lean)',238),
('Protein','Ground beef (90% lean)',202),
('Protein','Ground beef (95% lean)',167),
('Protein','Pastrami (beef)',98),
('Protein','Roast beef (eat lean & fat)',112),
('Protein','Roast beef (eat lean only)',83),
('Protein','Steak sandwich on roll',344),
('Protein','Steamed clams (oysters, mussels)',69),
('Protein','Steamed crab (hard shell)',48),
('Protein','Steamed dumpling, meat filled',41),
('Protein','Steamed or boiled crayfish',57),
('Protein','Steamed or boiled lobster',143),
('Protein','Steamed or boiled shrimp',155),
('Protein','Stir-fried beef, veggies & noodles',224),
('Protein','Stir-fried chicken & veggies on rice',234),
('Protein','Stir-fried chicken and vegetables',90),
('Protein','Stir-fried pork, vegetables & rice',245),
('Protein','Stir-fried shrimp and vegetables',79),
('Protein','Sweet & sour chicken',356),
('Protein','Sweet & sour pork',115),
('Protein','Sweet & sour pork on rice',268),
('Soup','Sweet & sour soup',73),
('Protein','Tamale (with meat or chicken)',133),
('Protein','Teriyaki steak with sauce',227),
('Protein','Tofu, firm',44),
('Protein','Tuna egg salad (with celery, mayo)',204),
('Protein','Tuna noodle casserole',423),
('Protein','Tuna salad (with celery, mayo)',191),
('Protein','Turkey bacon',42),
('Protein','Turkey breast lunch meat, fat free',24),
('Protein','Turkey lunch meat, fat free',29),
('Protein','Turkey sausage',59),
('Protein','Turkey with dressing frozen meal',484),
('Protein','Veal cutlet or steak, fried',139),
('Protein','Vienna sausage',45),
('Sauces','Cocktail sauce',55),
('Sauces','Barbeque sauce',24),
('Sauces','Dietetic jelly (low cal sweetener)',25),
('Sauces','Duck sauce',22),
('Sauces','Enchilada sauce',79),
('Sauces','Green tomato-chile sauce',46),
('Sauces','Hollandaise sauce',67),
('Sauces','Horseradish sauce',29),
('Sauces','Jam or preserves',55),
('Sauces','Jelly',51),
('Sauces','Lemon-butter sauce',107),
('Sauces','Pesto sauce',82),
('Sauces','Spaghetti sauce (meatless)',71),
('Sauces','Spaghetti sauce, fat-free (meatless)',51),
('Sauces','Steak sauce (A-1)',10),
('Sauces','Tartar sauce',74),
('Sauces','Tomato sauce',39),
('Sauces','Vinegar',2),
('Soup','Won ton soup',183),
('Sweets','Brown sugar',17),
('Sweets','Butterscotch sauce',63),
('Sweets','Calorie-free sweetener',1),
('Sweets','Chocolate icing',67),
('Sweets','Chocolate sauce (thin type)',52),
('Sweets','Dietetic syrup',6),
('Sweets','Dietetic topping',8),
('Sweets','Fruit topping',54),
('Sweets','Fudge sauce (thick type)',73),
('Sweets','Honey',64),
('Sweets','Marshmallow topping',20),
('Sweets','Nut topping (wet)',90),
('Sweets','Nutella (chocolate hazelnut spread)',84),
('Sweets','Powdered sugar (confectioners sugar)',10),
('Sweets','Sweet and sour sauce (Vietnamese Sauce)',28),
('Sweets','Syrup (all types)',53),
('Sweets','Vanilla or rum dessert sauce',95),
('Sweets','White icing',80),
('Sweets','White sugar (granulated or lump)',16),
('Vegetables','Artichoke',42),
('Vegetables','Bean salad (green, yellow, kidney beans)',57),
('Vegetables','Black olives',18),
('Vegetables','Blackeye peas',79),
('Vegetables','Boiled or steamed okra',18),
('Vegetables','Breaded fried mushrooms',148),
('Vegetables','Breaded fried summer squash',185),
('Vegetables','Breaded fried vegetable sticks',29),
('Soup','Broccoli cheese soup',165),
('Vegetables','Broccoli with cheese sauce',121),
('Vegetables','Broccoli-rice casserole',144),
('Vegetables','Caesar salad with dressing',168),
('Vegetables','Carrot juice',94),
('Vegetables','Carrot salad',208),
('Vegetables','Chef salad, no dressing',71),
('Vegetables','Chiles rellenos',365),
('Vegetables','Chives',1),
('Vegetables','Cilantro',1),
('Vegetables','Coleslaw',134),
('Vegetables','Cooked asparagus',17),
('Vegetables','Cooked bean sprouts',29),
('Vegetables','Cooked beets',37),
('Vegetables','Cooked broccoli',17),
('Vegetables','Cooked Brussels sprouts',33),
('Vegetables','Cooked cabbage',17),
('Vegetables','Cooked carrots',27),
('Vegetables','Cooked cauliflower',17),
('Vegetables','Cooked eggplant',35),
('Vegetables','Cooked green beans',14),
('Vegetables','Cooked green lima beans',104),
('Vegetables','Cooked green peas',66),
('Vegetables','Cooked hot peppers',18),
('Vegetables','Cooked mixed vegetables',59),
('Vegetables','Cooked mushrooms',22),
('Vegetables','Cooked onions',46),
('Vegetables','Cooked snowpeas',34),
('Vegetables','Cooked spinach',30),
('Vegetables','Cooked sweet peppers',19),
('Vegetables','Cooked tomatoes',22),
('Vegetables','Cooked turnip',17),
('Vegetables','Corn fritter',132),
('Vegetables','Corn pudding (scalloped corn)',128),
('Vegetables','Corn relish',51),
('Soup','Cream of broccoli soup',206),
('Soup','Cream of mushroom soup (made with milk)',191),
('Vegetables','Cream style corn',92),
('Vegetables','Creamed spinach',78),
('Vegetables','Cucumber',7),
('Vegetables','Dill pickle',5),
('Vegetables','Dried tomatoes',5),
('Vegetables','Eggplant Parmesan',317),
('Soup','French onion soup',58),
('Vegetables','Fried green tomatoes',212),
('Vegetables','Fried okra',87),
('Vegetables','Garlic',4),
('Vegetables','Green olives',21),
('Vegetables','Greens, cooked with fat',34),
('Vegetables','Greens, cooked without fat',18),
('Vegetables','Horseradish',7),
('Vegetables','Ketchup (catsup)',14),
('Vegetables','Kim chee (made from cabbage)',8),
('Vegetables','Lettuce',6),
('Soup','Minestrone soup',84),
('Vegetables','Mixed salad greens',9),
('Vegetables','Mustard',3),
('Vegetables','Onion rings',157),
('Vegetables','Parsley',0),
('Vegetables','Pea salad',250),
('Vegetables','Pickle relish',13),
('Vegetables','Pickled beets',27),
('Vegetables','Radish',0),
('Vegetables','Raw broccoli',12),
('Vegetables','Raw cabbage',14),
('Vegetables','Raw carrots',25),
('Vegetables','Raw cauliflower',13),
('Vegetables','Raw celery',8),
('Vegetables','Raw hot pepper (jalapeno)',19),
('Vegetables','Raw mushrooms',8),
('Vegetables','Raw onion',6),
('Vegetables','Raw spinach',7),
('Vegetables','Raw sweet pepper (bell pepper)',2),
('Vegetables','Raw tomatoes',6),
('Vegetables','Salsa',17),
('Vegetables','Sauerkraut',13),
('Vegetables','Sauteed green peppers & onions',40),
('Vegetables','Stew vegetables',58),
('Vegetables','Stewed tomatoes',33),
('Vegetables','Stuffed cabbage rolls (beef & rice)',117),
('Vegetables','Stuffed mushrooms (bread, meat & cheese)',67),
('Vegetables','Stuffed pepper (with rice and meat)',209),
('Vegetables','Succotash (lima beans and corn)',88),
('Vegetables','Sweet pickle (gherkin)',35),
('Vegetables','Tabasco sauce (hot sauce)',2),
('Vegetables','Taco salad with beef, cheese, corn chips',367),
('Vegetables','Tofu and vegetables (Monks food)',84),
('Vegetables','Tomato cucumber salad, with oil & vinegar',92),
('Vegetables','Tomato juice',41),
('Soup','Tomato soup (made with water)',85),
('Vegetables','Tossed salad (lettuce and vegetables)',12),
('Vegetables','V-8 juice (tomato-vegetable juice)',44),
('Vegetables','Vegemite',9),
('Soup','Vegetable beef soup (canned)',78),
('Soup','Vegetable beef soup (homemade)',229),
('Vegetables','Vegetable broth',17),
('Vegetables','Vegetable combo (Asian style)',23),
('Soup','Vegetable rice soup',106),
('Soup','Vegetable soup',82),
('Vegetables','Vegetable tempura',11),
('Vegetables','Vegetable-pasta combo',53),
('Vegetables','Vegetable-pasta combo with cream sauce',84),
('Vegetables','Water chestnut',40),
('Vegetables','Wrap sandwich (vegetables only)',472),
('Vegetables','Yellow corn (corn on the cob)',107),
('Vegetables','Zucchini or summer squash',18),
('Wraps & Sandwhiches','Wrap sandwich (meat, vegetables, rice)',818),
('Wraps & Sandwhiches','Wrap sandwich (vegetables, rice)',675),
('Carbohydrates','Corn Pops cereal',118),
('Protein','Corned beef hash',180),
('Protein','Crab cake',106),
('Fruit','Cranberry juice (100% juice)',116),
('Fruit','Cranberry sauce',105),
('Soup','Cream of chicken soup (with water)',117),
('Soup','Cream of tomato soup',146),
('Protein','Deli chicken or turkey loaf',43),
('Protein','Deli ham (extra lean)',37),
('Protein','Deli ham (regular)',45),
('Protein','Deli sliced roast beef',50),
('Protein','Deli sliced turkey or chicken breast',29),
('Protein','Double cheeseburger on double deck bun',620),
('Protein','Double hamburger on bun',384),
('Fruit','Dried fruit (apricot, apple, etc.)',86),
('Protein','Egg roll with meat',113),
('Vegetables','Egg roll with vegetables',100),
('Fruit','Fig (dried)',47),
('Carbohydrates','French fries, oven-baked',113),
('Fruit','Frozen fruit juice bar',61),
('Fruit','Fruit cocktail (canned in heavy syrup)',82),
('Fruit','Fruit cocktail (canned in light syrup)',64),
('Fruit','Fruit salad (no dressing)',48),
('Fruit','fruit smoothie (no milk)',326),
('Soup','Fruit soup',177),
('Protein','Gefilte fish',77),
('Protein','General Tso chicken',148),
('Vegetables','Glazed carrots',101),
('Fruit','Grape juice (100% juice)',154),
('Fruit','Grapefruit (canned, light syrup)',76),
('Fruit','Grapefruit (raw)',41),
('Fruit','Grapefruit juice (unsweetened)',94),
('Fruit','Grapes (raw)',55),
('Vegetables','Greens with ham or pork',39),
('Protein','Ground turkey',140),
('Vegetables','Guacamole',91),
('Fruit','Guava (raw)',46),
('Soup','Gumbo (with rice, New Orleans type)',193),
('Protein','Ham salad spread',273),
('Protein','Ham sandwich with mayo',271),
('Protein','Hamburger, plain on bun',270),
('Fruit','Honeydew melon (raw)',45),
('Soup','Hot & sour soup',161),
('Protein','Hot dog (frankfurter)',175),
('Protein','Imitation crabmeat',72),
('Protein','Jambalaya (with meat & rice)',393),
('Fruit','Kiwifruit (raw)',46),
('Protein','Kung Pao chicken',217),
('Protein','Lamb chop',224),
('Protein','Lemon chicken',335),
('Fruit','Lemon juice',4),
('Protein','Liver and onions',177),
('Protein','Lo mein (meatless)',234),
('Protein','Lobster bisque',248),
('Protein','Low fat bologna',64),
('Protein','Low fat hot dog',92),
('Fruit','Low-calorie frozen fruit juice bar',24),
('Carbohydrates','Lucky Charms cereal',110),
('Carbohydrates','Macaroni and cheese (from dry mix)',198),
('Carbohydrates','Macaroni and cheese (homemade type)',237),
('Carbohydrates','Macaroni and cheese with beef',168),
('Carbohydrates','Macaroni salad',170),
('Carbohydrates','Macaroni salad with egg',179),
('Protein','Maki sushi (rolled sushi with veggies)',30),
('Fruit','Mandarin oranges (light syrup)',77),
('Fruit','Mango (raw)',54),
('Fruit','Maraschino cherries',7),
('Carbohydrates','Mashed sweet potato',107),
('Soup','Matzo ball soup',118),
('Protein','Meat & cheese calzone or stromboli',738),
('Protein','Meat & veggie pizza, thick crust',233),
('Protein','Meat & veggie pizza, thin crust',193),
('Protein','Meat and cheese quesadilla',605),
('Protein','Meat and cheese turnover (Hot Pockets)',358),
('Protein','Meat lasagna',321),
('Protein','Meat pizza, thick crust',243),
('Protein','Meat pizza, thin crust',208),
('Protein','Meat ravioli with tomato sauce',104),
('Protein','Meatball Sub',611),
('Protein','Meatloaf or meatball, no sauce',220),
('Protein','Meatloaf or meatballs & tomato sauce',240),
('Soup','Mexican beef vegetable soup',143),
('Soup','Mexican chicken vegetable soup with rice',182),
('Sauces','Mushroom gravy',16),
('Fruit','Nectarine (raw)',60),
('Soup','New England clam chowder',149),
('Protein','Nigiri sushi (with fish and veggies)',36),
('Carbohydrates','Noodle pudding',148),
('Fruit','Orange (raw)',62),
('Fruit','Orange juice (100% juice)',105),
('Fruit','Orange juice (sweetened)',130),
('Fruit','Papaya (raw)',59),
('Protein','Pasta salad with meat and vegetables',148),
('Carbohydrates','Pasta salad with vegetables',117),
('Fruit','Peach (canned in light syrup)',53),
('Fruit','Peach (raw)',38),
('Fruit','Peach nectar',134),
('Fruit','Pear (canned in light syrup)',43),
('Fruit','Pear (raw)',96),
('Vegetables','Peas and carrots',38),
('Protein','Pepperoni',26),
('Soup','Pepperpot soup or menudo soup',104),
('Fruit','Persimmons (raw)',118),
('Protein','Philly cheese steak (pepper, onion, roll)',486),
('Protein','Pig in a blanket (hot dog in dough)',275),
('Fruit','Pineapple (canned in light syrup)',66),
('Fruit','Pineapple (raw)',37),
('Fruit','Pineapple juice (100% juice)',140),
('Protein','Pizza rolls or bites',42),
('Fruit','Plum (raw)',30),
('Protein','Polish sausage',234),
('Fruit','Pomegranate (raw)',52),
('Protein','Pork or ham with BBQ sauce',237),
('Protein','Pork spareribs (eat lean & fat)',533),
('Protein','Pork spareribs (eat lean only)',205),
('Protein','Pork, veggies and noodles (tomato sauce)',408),
('Carbohydrates','Potato sticks',99),
('Protein','Pozole',195),
('Carbohydrates','Pringles potato chips',240),
('Fruit','Prune juice (100% juice)',182),
('Fruit','Prunes',204),
('Protein','Quarter pound cheeseburger on bun',552),
('Protein','Quarter pound hamburger on bun',459),
('Protein','Quiche (with meat, poultry or fish)',568),
('Carbohydrates','Raisin bran cereal',195),
('Soup','Ramen noodle soup',170),
('Fruit','Raspberries (raw)',32),
('Carbohydrates','Raw bean sprouts',16),
('Carbohydrates','Reduced fat potato chips (all flavors)',94),
('Carbohydrates','Rice and beans',196),
('Carbohydrates','Rice Chex cereal',124),
('Carbohydrates','Rice Krispies cereal',94),
('Carbohydrates','Rice with tomato sauce',126),
('Carbohydrates','Rice with vegetables',139),
('Protein','Roast beef sandwich',369),
('Protein','Roast pork (lean)',87),
('Protein','Roast pork tenderloin',195),
('Protein','Roasted Cornish game hen',285),
('Protein','Roasted duck',255),
('Protein','Roasted turkey (white & dark meat)',47),
('Protein','Roasted turkey (white meat)',44),
('Protein','Roasted veal',97),
('Protein','Roasted venison',215),
('Protein','Salisbury steak frozen meal',462),
('Protein','Salisbury steak with gravy',218),
('Protein','Sausage biscuit',438),
('Sauces','Sausage gravy',187),
('Protein','Sausage, egg, and cheese croissant',539),
('Carbohydrates','Scalloped potatoes',108),
('Protein','Seafood salad (with tomatoes, dressing)',163),
('Protein','Seafood stuffed shells with tomato sauce',306),
('Carbohydrates','Shredded wheat cereal',170),
('Protein','Shrimp fried rice',161),
('Protein','Shrimp lo mein',236),
('Protein','Shrimp with pasta diet frozen meal',290),
('Protein','Smoked ham (lean)',66),
('Protein','Smoked salmon (lox)',23),
('Fruit','Sorbet (made with fruit)',82),
('Protein','Spaghetti sauce (with meat)',141),
('Protein','Spaghetti with meat sauce',350),
('Protein','Spaghetti with tomato sauce (meatless)',250),
('Carbohydrates','Spanish rice',106),
('Carbohydrates','Special K cereal',117),
('Vegetables','Spinach lasagna (vegetarian)',279),
('Vegetables','Spinach quiche',342);

COMMIT;
